### PR TITLE
update user feature blog

### PR DESCRIPTION
**Pull request by dmuelle**
updated post on draft: https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2022/07/06/user-feature-install.html

### CODE REVIEW

**Comment by dmuelle** [comment]
Hi @jjiwooLim - would you review this PR to add your updates to staging and approve if everything looks right?

**Review by jjiwooLim — CHANGES_REQUESTED** [review]
I forgot to update the dependencies on line 56
It should be updated to 
```
<dependency>
    <groupId>org.osgi</groupId>
    <artifactId>org.osgi.framework</artifactId>
    <version>1.10.0</version>
</dependency>
```

Also, line 52 should be changed to 
. Add the `org.osgi.framework` dependency to import `org.osgi.framework` package:

**Comment by dmuelle** [comment]
updated

**Review by jjiwooLim — APPROVED** [review]
LGTM! Thank you :)

**Pull request merged**
