### PR TITLE
Removing all tags + references to Red Hat Release Notes from templates

### PR DESCRIPTION
**Pull request by jakub-pomykala**

### CODE REVIEW

**Review by dmuelle — DISMISSED** [review]
LGTM thanks

**Comment by gljrobinson** [comment]
@jakub-pomykala has this work been completed or are we still working on this?

**Comment by jakub-pomykala** [comment]
@GraceJansen this PR should be ready to merge

**Review by gljrobinson — APPROVED** [review]
LGTM

**Pull request merged**
