### PR TITLE
Fix link to GraphQL guide

### PR DESCRIPTION
**Pull request by lauracowen**
Missing 'l' on file suffix

### CODE REVIEW

**Comment by lauracowen** [comment]
Sorry, @kinueng , both David and Ryan are on vacation at the moment.

**Comment by gkwan-ibm** [comment]
hi @lauracowen
The mp-graphql guide is not updated to use mpGraphQL-2.0 yet. We are working on it, because it was just released in OL 22.0.0.6.

**Comment by lauracowen** [comment]
@gkwan-ibm I don't think that's a problem. The post (which is already published; I'm just fixing the broken link that was already in there) is pointing to the guide to find out more about GraphQL. It's not saying it's 2.0 (which is fairly normal for the release blog posts).

**Comment by kinueng** [comment]
The broken link in the blog post is 
[Optimizing REST queries for microservices with GraphQL](https://openliberty.io/guides/microprofile-graphql.htm)
- URL is incorrectly ending with `.htm` https://openliberty.io/guides/microprofile-graphql.htm

Fix is to make the URL be
https://openliberty.io/guides/microprofile-graphql.html

**Review by kinueng — APPROVED** [review]
LGTM

**Pull request merged**
