### PR TITLE
Japanese translate for 2024-05-21-24.0.0.5.adoc blog entry

### PR DESCRIPTION
**Pull request by MiyukaNishio**
@MiyukaNishio send Pull Request for Japanese Blog Entry for 24.0.0.5 update.

### CODE REVIEW

**Comment by MiyukaNishio** [comment]
@una-tapa こちらドラフトサイトでの反映が確認できないのですが、ご確認いただけますでしょうか。
お手数ですがよろしくお願いいたします。

**Comment by una-tapa** [comment]
@dmuelle When you get a chance, please take a look at this PR.  Thank you! (cc: @MiyukaNishio )

**Review by dmuelle — APPROVED** [review]
LGTM- approving so we can preview the result on draft and making changes as needed

**Review by dmuelle — APPROVED** [review]

**Comment by dmuelle** [comment]
@MiyukaNishio @una-tapa the translation is now avaialble for review on draft:

https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/ja/blog/2024/05/21/24.0.0.5.html

If it looks ok, @MiyukaNishio please open a PR from your `MiyukaNishio:Japanese-translate` branch to `OpenLiberty:staging` and assign me as the reviewer. Thanks!

**Pull request merged**
