### PR TITLE
Correct issuerIdentifier OIDC client attribute references in Sep 2022 post

### PR DESCRIPTION
**Pull request by ayoho**
The https://openliberty.io/blog/2022/09/27/22.0.0.10.html#oidc post (and corresponding Japanese post) contains incorrect references to an `issuer` attribute in the `openidConnectClient` configuration element. Those references need to be updated to say `issuerIdentifier` instead.

### CODE REVIEW

**Comment by ayoho** [comment]
@GraceJansen Would you be available to review this?

**Review by gljrobinson — APPROVED** [review]
Changes all look good to me.

**Comment by gljrobinson** [comment]
@ayoho Just reviewed it and the changes all looks good to me, clear swap out and no other changes. I've approved but I don't have the necessary permissions to merge.

**Comment by mbroz2** [comment]
Looks good on draft: https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2022/09/27/22.0.0.10.html
image

**Pull request merged**
