### PR TITLE
PR for finding_fixpacks to staging

### PR DESCRIPTION
**Pull request by barbj**

### CODE REVIEW

**Comment by barbj** [comment]
Staging for #1432

**Comment by barbj** [comment]
Draft of article: https://draft-openlibertyio.mybluemix.net/blog/2021/05/21/finding-liberty-fixpack.html

**Comment by barbj** [comment]
image
image
image

**Comment by barbj** [comment]
@NottyCode I asked you to be the technical reviewer because more than one person said that you should review this.  I wouldn't want to not comply!

**Comment by barbj** [comment]
@NottyCode @GraceJansen @dmuelle Will one of you please review this?  I need to get this out in order to be able to send customers to it from SF cases.  I've already had to send them to this PR for them to read a picture of the instructions, which isn't so cool.

**Review by dmuelle — APPROVED** [review]

**Pull request merged**
