### PR TITLE
Add splunk blog

### LINKED ISSUE #314: Using Open Liberty Logging with Splunk
Blog about how to analyze Open Liberty logs with Splunk, using Docker containers.

Laura: Aim at publishing Wed 27th May.

### PR DESCRIPTION
**Pull request by pgunapal**
fixes #314

### CODE REVIEW

**Review by donbourne — APPROVED** [review]

**Comment by dmuelle** [comment]
Hi @pgunapal, can you re-create this PR  according to the new blog contributor guidelines : https://github.com/OpenLiberty/blogs/blob/draft/README.md

Once the draft is built, I can provide ID review. Thanks

**Comment by dmuelle** [comment]
Hi @pgunapal - looks like you may need to reclone this repo to get the updated directory structure. Per the new README instructions:

- clone the repo
- create a personal branch (name whatever you choose) based on the `prod` branch
- copy your file into the  `posts` directory with the name in the format `2020-05-27-how-to-analyze-open-liberty-logs-with-splunk.adoc`
- open a PR from your branch to the `draft` branch and assign me as a reviewer

Thanks!

**Comment by pgunapal** [comment]
@dmuelle Thanks David, will do that and let you know.

**Comment by pgunapal** [comment]
@dmuelle Created a new PR #416 in draft branch for your review. Closing this as dup.

**Pull request closed without merging**
