### PR TITLE
Merge the Jakarta NoSQL blogposts into draft

### PR DESCRIPTION
**Pull request by dearrudam**
Ref: https://github.com/OpenLiberty/blogs/issues/3536

- Update code blocks to use the updated API of Eclipse JNoSQL and Jakarta Data API

### CODE REVIEW

**Comment by dearrudam** [comment]
It is a continuation of https://github.com/OpenLiberty/blogs/pull/3695

@fabio-franco, could you review it?

**Comment by fabio-franco** [comment]
New draft available for review at: https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/

**Comment by dearrudam** [comment]
Thank you so much @fabio-franco !!! Also, I need to fix some broken links, sorry about that 👍 ... I'll open a new PR for that!

**Comment by fabio-franco** [comment]
No problem! That's part of the review. I am happy to update the repo whenever necessary. 😄

**Pull request merged**
