### PR TITLE
Update ol stack blog to use app demo branch

### PR DESCRIPTION
**Pull request by awisniew90**
Signed-off-by: Adam Wisniewski <awisniew@us.ibm.com>

Issue: #1202

### CODE REVIEW

**Comment by gljrobinson** [comment]
Hi @dmuelle, would you mind taking a quick look at this please?

**Comment by awisniew90** [comment]
Hi @dmuelle / @GraceJansen  - this is still WIP, but I should have something ready next week.

**Comment by awisniew90** [comment]
Hi @dmuelle - This is all set to review now 👍

**Review by dmuelle — DISMISSED** [review]
LGTM- but I'd recommend including the typo fix from #1363 in this PR so you can deliver them to staging together- unless there's a reason to use two branches/PRs that I'm overlooking

**Comment by awisniew90** [comment]
@dmuelle  - good point. I added the change here and closed the other PR.

**Review by dmuelle — APPROVED** [review]

**Comment by dmuelle** [comment]
Great- can you open a PR from this branch to staging? The update can publish later today

**Pull request merged**
