### PR TITLE
Libertydevops 1 gitjenkinshelmiks

### PR DESCRIPTION
**Pull request by shamjithantholi**
please merge

### CODE REVIEW

**Review by yeekangc — COMMENTED** [review]
Let us discuss further and please consider what is suggested in https://github.com/OpenLiberty/blogs/issues/2217.

**Review by yeekangc — CHANGES_REQUESTED** [review]
Need to address what is noted in #2217 first.

**Review by lauracowen — APPROVED** [review]
I'm going to approve this into draft so that we can see it built. I'll then do an editorial review, which might still involve changes, but it'll be easier to follow than keep doing it by issue.

**Comment by lauracowen** [comment]
I'm merging as most of the changes have been made and it'll be easier to review and edit if we get it built to draft.

**Pull request merged**
