### PR TITLE
Fix blog author's GitHub profile picture

### PR DESCRIPTION
**Pull request by kinueng**
Update @KyleAure blog post with new profile picture url

# Problem
image

### CODE REVIEW

**Review by dmuelle — DISMISSED** [review]
LGTM- though I'm not sure why there are conflicts in the blog tags file

**Comment by kinueng** [comment]
I am still having issues trying to get this PR to only have my changes.  I will have to revisit this PR again at another time.

**Comment by dmuelle** [comment]
@kinueng - FWIW, all the extra changes are already in draft and should not constitute an actual conflict. I think it's just Git reacting to the commit SHAs from when staging was merged into prod, which haven't been synched back draft yet.

**Comment by kinueng** [comment]
I was unable to spend the time to confirm if the changes intentionally attached to this PR was in draft already or not.  Thank you for confirming and I will go ahead with merging once reviewed again.

**Review by dmuelle — COMMENTED** [review]
LGTM thanks

**Review by dmuelle — APPROVED** [review]

**Pull request merged**
