### PR TITLE
Create ELK-stack-dashboards.adoc

### PR DESCRIPTION
**Pull request by leemelim**
Create ELK stack dashboards blog

### CODE REVIEW

**Comment by donbourne** [comment]
@leemelim , a few comments...

title: 
    - ELK Stack Dashboard Improvements for JSON Logging and the Logstash Collector version 1.0
    -> 
    - Open Liberty Kibana Dashboard Improvements
    
intro:
    you need a paragraph to say...
    - that log aggregation and analysis is important
    - that the Elastic Stack is one set of tools that people use to aggregate and analyze their logs
    - that there are sample Kibana dashboards for Liberty
    - that you can use them with logstashCollector-1.0 feature or with the logs from JSON logging
    
Problem Dashboard
    - rename to Problems Dashboard (that's how we usually refer to it)
    - The Problem dashboards now include -> The Problems dashboard now includes
    - The numbers help you see how many potential problems have occurred -> The numbers make it easy to see at a glance how many potential problem log entries have been collected.
    - Both Liberty Message and Liberty Trace graphs are filtered by log levels/severity and you can easily grasp how healthy your server is running.
      ->
      Both Liberty Message and Liberty Trace graphs are broken down by log levels/severity and you can easily see when problems occurred.  Click on any of the severities in the legend to add a filter.

**Comment by donbourne** [comment]
a few more comments...


The Problems dashboard now includes a new visualization -> The Problems dashboard includes a new visualization

By using the ELK stack dashboards -> By using Kibana dashboards

JSON Logging or Logstash Collector -> JSON logging or Logstash collector

how healthy and responsive your Liberty servers are performing. -> how healthy and performant your Liberty servers are.

**Comment by leemelim** [comment]
Hi Laura, would you like us to state the exact release of when JSON logging and logstashCollector were enabled in Open Liberty? Or can we say that the dashboards can be used with any current OpenLiberty releases?

**Comment by lauracowen** [comment]
> Hi Laura, would you like us to state the exact release of when JSON logging and logstashCollector were enabled in Open Liberty? Or can we say that the dashboards can be used with any current OpenLiberty releases?

Hi - you don't need to state anything. I was asking for myself so that I can make sure I provide the right links etc when I edit it. Just let me know here. Thanks

**Comment by leemelim** [comment]
> > Hi Laura, would you like us to state the exact release of when JSON logging and logstashCollector were enabled in Open Liberty? Or can we say that the dashboards can be used with any current OpenLiberty releases?
> 
> Hi - you don't need to state anything. I was asking for myself so that I can make sure I provide the right links etc when I edit it. Just let me know here. Thanks

Liberty 18.0.0.1 or later is required to output messages in JSON format.
I believe logstashCollector was enabled in late 2016 and the dashboards require Liberty releases after that.

The blog file is edited for your review.

**Pull request merged**
