### PR TITLE
2024-03-29 Getting Started with Liberty Project blog

### PR DESCRIPTION
**Pull request by Ruilin-Ma**
Issue related to this PR: https://github.com/OpenLiberty/blogs/issues/3517

Draft site for reviewing the blog: http://lg-dev1.fyre.ibm.com:4022/blog/2024/04/05/liberty-project-starter-guide.html

### CODE REVIEW

**Review by lauracowen — CHANGES_REQUESTED** [review]
This is a good start, thanks @Ruilin-Ma . I think there are some aspects missing from the outline Gilbert provided in the issue, but also I think the post (and Gilbert's outline) can be both simplified and explained more yet.

Put yourself back into the position of a student/recent grad who's never worked with Liberty or other app runtimes ([point them to Yasmin's post for more info about that](https://openliberty.io/blog/2020/11/19/app-server-intro.html)), or enterprise Java, or Maven, or "starters". Then focus on how you'd feel when faced with a clean machine and you just want to know as quickly and simply as possible how to start creating an enterprise Java app (tell them to run the starter), or using Maven (tell them to install Maven and how and what a build tool does for them), or installing a Java distribution (tell them to install Semeru and how). This is not the fun stuff; they really want to write and run an app. Get them to the fun stuff as quickly as possible with as few options or places they can go wrong as possible.

Some things to consider along the way:

* The prerequisites section needs to point the user to where to get Java from. I think I would point them to [IBM Semeru installation instructions](https://www.ibm.com/support/pages/semeru-runtimes-installation). At the end of the post could provide a section called something like "Find out more" and say "(there are multiple Java distributions; find out more in [Where do you get your Java?](https://foojay.io/today/where-do-you-get-your-java/))." (or something like that - you're not trying to divert them elsewhere, you're just trying to provide helpful info if they need to understand more.). Would you agree/disagree @yeekangc @GraceJansen ?
* The info in this sentence later "To enable Liberty development mode, please ensure that the JAVA_HOME environment variable has been properly set up so that you can activate it using following commands in the terminal:" should be in the prereqs section which is when you should check the JAVA_HOME env var (why do you need it? how do you check it? And how do you set it? point to some docs or briefly describe it).
* In the prereqs section I think you also need to say what build tools are for (eg pulling down an instance of the Open Liberty runtime). And point to instructions for how to install one (as I remember it, it's not that easy to install Maven?). To be honest, I'd would keep this really simple and not even tell them about Gradle at this point - just tell them to install Maven - don't complicate things - you can have a link to Gradle at the end of the post or something but don't give them lots of options here, the reader wants a simple experience and wants you to guide them through it all prescriptively - as few options as possible.
* When it comes to describing the Maven stuff in the project, just describe what the pom does and if they need to modify anything in it at this stage.
* If you're working in an IDE, they should probably actually install Liberty Tools before they create and import the project. Then they can see how Liberty Tools handles the project when it's been imported. Otherwise, there's a chance they'll import the project and not realise they need to install the Tools still to work with it. @GraceJansen might be able to help more here as she's recently written some articles (that should maybe also link to for more info or at the end of this post)
* I think the "next step" after finishing this blog post tutorial is to do the Getting Started guide really and then the REST guide (I'm not sure I'd just overwhelm them with links to all the MP and JEE guides at this stage). The request for this blog post was to fill the gap between a clean machine and being able to start doing the OL Getting Started guide.

**Comment by gljrobinson** [comment]
Agree with all of Laura's comments here. 

I agree with Laura on simplifying the prereqs for where to get Java. Let's point them to Semeru and then at the end of the article we can maybe have a section which covers all the alternatives they could possibly use including links to relevant articles and blogs (e.g. can use other Java + link to Rich's article, and could point our Gradle as an alternative build tool, etc).

Yes, thanks Laura, @Ruilin-Ma it would be useful if we could have them install the tools plugins (either Eclipse, VS Code or IntelliJ IDEA). We have three articles (one for each plugin) on IBM Developer that goes into detail on what each plugin offers and how to use them. Can link off to this and just give simple instructions to download plugin either in IDE itself or in corresponding marketplace. 
Links for this:
[VS Code](https://developer.ibm.com/articles/awb-effective-cloud-native-development-open-liberty-vs-code/)
[IntelliJ IDEA](https://developer.ibm.com/articles/awb-effective-cloud-native-development-open-liberty-intellij-idea/)
[Eclipse IDE](https://developer.ibm.com/articles/awb-effective-cloud-native-development-open-liberty-eclipse-ide/)

Agree with Laura that we should try and keep this simple and as easy as possible. Laura's suggested next steps seem sensible to me and help to avoid potentially overwhelming them with too many guides and topics to choose from and perhaps not knowing where to go/start with them.

**Comment by Ruilin-Ma** [comment]
Hi @lauracowen and @GraceJansen, thank you for the suggestions. The latest version of the blog has addressed most of your suggestions, except for the guidance on installing Maven. Currently, we are using the Liberty Starter + Liberty Tools approach to facilitate the swift and straightforward creation of Open Liberty projects. The Liberty Starter includes a Maven wrapper, allowing users to initiate Liberty projects without the need for Maven installation. Users can use the Liberty Tools discussed in the blog to run Liberty projects. 

Following discussions with @yeekangc and @gkwan-ibm, we are thinking to prioritize the use of Liberty Tools over the command line. In this case, I have updated the content in the section `Developing your application using Liberty dev mode and Liberty Tools` by placing the content related to Liberty Tools ahead of the command line instructions. Please let me know your thoughts and feel free give comments on the [updated version of the blog](http://lg-dev1.fyre.ibm.com:4022/blog/2024/04/05/liberty-project-starter-guide.html). Thank you!

**Review by lauracowen — CHANGES_REQUESTED** [review]
Hi, I think the overall blog structure looks ok now, thanks.
Can you ask @dmuelle to do an ID review/edit of the post for style, please? I wasn't able to do that and I think it's important as this is to be a clear introductory set of instructions that may end up being a guide.

**Comment by lauracowen** [comment]
I don't have a strong view about prioritising Tools over the cmdline.

I think the post would actually be stronger/clearer (for SEO too) if you just showed Intellij and Maven. This isn't really documentation, it's a means of getting someone new up to speed. Just give them the easiest experience with the most likely tools. Then provide link to others. We could subsequently create a separate post for each IDE, but start with the most likely.

@yeekangc do you have a preference/thoughts?

**Comment by yeekangc** [comment]
Good with Liberty Tools over CLI and to work with our tools for IntelliJ IDEA here.

**Pull request closed without merging**
