### PR TITLE
Emily instant on fix

### PR DESCRIPTION
**Pull request by mbroz2**

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
Can you also take the other 2 files https://github.com/OpenLiberty/blogs/pull/3206/files

**Review by Emily-Jiang — APPROVED** [review]
LGTM! Thanks @mbroz2 !

**Review by Emily-Jiang — DISMISSED** [review]
Can you also pull in the PR #3214

**Comment by Emily-Jiang** [comment]
@mbroz2 any chance to pick one last change and move this forward?

**Review by dmuelle — APPROVED** [review]
LGTM

**Pull request merged**
