### PR TITLE
ID edits- Gilberts post

### PR DESCRIPTION
**Pull request by dmuelle**

### CODE REVIEW

**Review by gljrobinson — DISMISSED** [review]
LGTM

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
I didn't see my recent updates in this PR:
- line 54: 
> ~~, including communication skills~~.  Following this, I joined IBM, IBM gave me opportunities to improve my communication skills, and ironically, ...

- line 79:
> ... initially, and more guides were published continuously.

- line 89:
  - should be 21  instead of 19

**Comment by dmuelle** [comment]
@gkwan-ibm - looks like there was more than one branch used to edit this doc. I found grace's `blogGilbert_Grace` and made changes there, but I guess that branch did not have the most recent changes.

I tried to address the three changes from your comment and pushed a new commit. Let me know if further changes are needed. Thanks

**Review by gkwan-ibm — DISMISSED** [review]
I saw some spacing at 
- line 27:
  - `edition,  and tWAS`  - double spaces 
- line 37:
  - `As of  July 2021,` - double spaces 
- line 80: 
  - `2021,  link:` - 2 spaces
  -  `continuously . Developers` - a space before period

**Comment by dmuelle** [comment]
@gkwan-ibm - I made those fixes in a new commit, can you reapprove?

**Review by gkwan-ibm — APPROVED** [review]

**Pull request merged**
