### PR TITLE
Add blog for using the Open Liberty devfile stack

### PR DESCRIPTION
**Pull request by awisniew90**
This PR is to add a blog for using the Open Liberty devfile stack (adding 2020-12-4-open-liberty-devfile-stack.adoc).

### CODE REVIEW

**Comment by awisniew90** [comment]
Fixes issue #868

**Comment by gljrobinson** [comment]
@awisniew90 has this undergone a technical review yet?

**Comment by awisniew90** [comment]
Hi @GraceJansen - it's currently under review but should be wrapping up soon.

**Comment by scottkurz** [comment]
@awisniew90  maybe just spell out the part where you grab the `odo url list` output and concat it with /api/resource..just show the output window and then show:  `curl http://<host>/api/resource`  as a next step.   Just a bit clearer and not much extra.  

I was going to paste a curl one-liner and realized it got messed up by a warning that I wasn't using the latest 'odo' just released... so, maybe forget the one-liner then .

**Comment by awisniew90** [comment]
@scottkurz  - Updated. Let me know what you think.

**Comment by awisniew90** [comment]
replaced with #941

**Pull request closed without merging**
