### PR TITLE
Forwarding Open Liberty logs in OpenShift Container Platform to Splunk using Log Forwarding API blog

### PR DESCRIPTION
**Pull request by Channyboy**
Issue: #848
Draft build: https://draft-openlibertyio.mybluemix.net/blog/2020/10/20/ocp-log-forwarding.html

### CODE REVIEW

**Comment by Channyboy** [comment]
@lauracowen 
Is there an estimate for the review?

**Comment by lauracowen** [comment]
@Channyboy Sorry, for not responding so far. The two posts above you on the editing backlog will hopefully be done in the next week or so so it'd be you next.

Does this post relate to function in a specific release?

**Comment by Channyboy** [comment]
@lauracowen it sort of goes along with what Red Hat is doing for OCP. They just GA-ed 4.6 so just made some updates to reflect that.

**Comment by Channyboy** [comment]
https://draft-openlibertyio.mybluemix.net/blog/2020/11/09/ocp-log-forwarding.html
*forgot to link to new draft

**Comment by Channyboy** [comment]
@lauracowen Is there an updated time-line.
When this goes through, will the file-nam / date  be updated?

**Comment by lauracowen** [comment]
@Channyboy Hi, no, we're overloaded with editing at the moment so we're working through in the order of the editorial backlog column (shown in zenhub).

Yes, the filename/date will be updated appropriately.

**Comment by Channyboy** [comment]
Hi @lauracowen 
Is there an updated ETA?
I see that #651 is already in the backlog? This item and that item are related.
This issue was created at your request from : https://github.com/OpenLiberty/blogs/pull/652
I was unaware that https://github.com/OpenLiberty/blogs/issues/651 existed.

**Comment by lauracowen** [comment]
> I see that #651 is already in the backlog? This item and that item are related.
> This issue was created at your request from : #652
> I was unaware that #651 existed.
I know, I think I created one because I couldn't find yours. I noticed yours since. Can you delete whichever you want and associate your PR with the one you want to keep?

> Is there an updated ETA?
Sorry, I was hoping to do your review/edit last week but had to work on something else. I'm currently handing over this work before I go on leave, and there isn't a direct replacement for me on the blogs yet (hopefully sort that out this/next week). In the meantime, I've had to work on something else so that I can hand over that in time too.

**Review by gljrobinson — DISMISSED** [review]
LGTM

**Review by dmuelle — APPROVED** [review]
LGTM

**Pull request merged**
