### PR TITLE
Blog post for Liberty Maven/Gradle plugins with dev mode for containers

### PR DESCRIPTION
**Pull request by ericglau**
Part of https://github.com/OpenLiberty/blogs/issues/857

Content for review: https://github.com/OpenLiberty/blogs/blob/devcrelease/posts/2020-12-18-dev-mode-container-liberty-maven-gradle-plugins.adoc

- Draft website builds are unavailable at the moment
- You can ignore the other files in the PR since those are just due to how the branches are being merged

### CODE REVIEW

**Comment by ericglau** [comment]
@yeekangc @GraceJansen Can you please review the blog post at https://github.com/OpenLiberty/blogs/blob/devcrelease/posts/2020-12-04-dev-mode-container-liberty-maven-gradle-plugins.adoc

**Review by yeekangc — DISMISSED** [review]
LGTM.  Thanks!

**Comment by yeekangc** [comment]
Approved from a technical standpoint.  Thank you, @ericglau.  As discussed, we should align with the upcoming fix releases.

@GraceJansen, this should be prioritized high since this relates to new capabilities that we want to share with the community.

Cc @Charlotte-Holt @dmuelle

**Comment by ericglau** [comment]
Updated the version numbers and publish date to align with the upcoming plugin releases.

**Comment by ericglau** [comment]
@yeekangc Can you please reapprove? (The latest commits automatically dismissed your review)

**Review by yeekangc — DISMISSED** [review]

**Comment by ericglau** [comment]
@GraceJansen Can you please review for publishing?

**Comment by gljrobinson** [comment]
Hi @ericglau, thanks for tagging me. I have placed this into our backlog of blogs to review. 
Due to the Christmas break we've got a backlog of blogs to work through and so at the moment your blog is not scheduled to be published until the end of January/beginning of February, as there are blogs that are of higher priority and have been waiting for review for longer. I'll keep you updated as to when this is assigned a reviewer.

**Review by dmuelle — APPROVED** [review]

**Pull request merged**
