### PR TITLE
add jenkins cic-cd post tags to staging

### PR DESCRIPTION
**Pull request by dmuelle**

### CODE REVIEW

**Review by kinueng — DISMISSED** [review]
LGTM

**Review by mbroz2 — COMMENTED** [review]
I think you got the key ones, but I would suggest also adding `test` tag (could also add `security` though that part is pretty sparse.....)

**Comment by dmuelle** [comment]
updated to add security tag

**Review by gljrobinson — APPROVED** [review]
LGTM

**Pull request merged**
