### PR TITLE
Mp perf collateral update

### PR DESCRIPTION
**Pull request by tpickett1**
Update this blog post with newest Performance data/charts.

### CODE REVIEW

**Comment by tpickett1** [comment]
If there is a why we could tweet or other form of external notice that this post has updated performance data, it would be great.

**Review by mbroz2 — CHANGES_REQUESTED** [review]
This new performance data should be moved to a new blog post.  The old 2020-10-21-memory-footprint-throughput.adoc post can be updated to point people at the new post via a link.

**Comment by tpickett1** [comment]
ok, I'll work on the new post with Graham, and once that is done I'll update the old blog post with a link to the new one.
Thanks.

**Comment by gljrobinson** [comment]
Hi @tpickett1, as you published a separate blog with Graham, is this PR ok to be closed?

**Comment by tpickett1** [comment]
yes, it can be closed

**Pull request closed without merging**
