### PR TITLE
add tags for Jaime's post

### PR DESCRIPTION
**Pull request by dmuelle**
#1566-
 this PR includes changes I didn't make, including multiple changes to the release post slugs. The only change I made was to add `open-liberty-semeru-performance` to the `community`, `developer experience`, and `performance enhancements` tags

### CODE REVIEW

**Comment by mbroz2** [comment]
something seems wrong here, as it's reverting a bunch of updates to tags that the core site team made for the purpose of linking to blog posts from /start.

**Comment by mbroz2** [comment]
I just checked `prod` and `staging` and they correctly have the proper tags, which leads me to believe that the [blog-tags-jamie](https://github.com/OpenLiberty/blogs/tree/blog-tags-jamie) branch is well behind `prod` and needs to pull in the updates from it.

**Review by mbroz2 — CHANGES_REQUESTED** [review]
[blog-tags-jamie](https://github.com/OpenLiberty/blogs/tree/blog-tags-jamie) needs to merge `prod` to pull in updates to the blog-tags-json file.  Alternatively, @dmuelle you can just create a different, new branch off of `prod` to add your tags.

**Comment by dmuelle** [comment]
Weird- I just created this branch off prod about 10m minutes ago- should I recreate the changes from a staging-based branch?

**Comment by dmuelle** [comment]
I just realized the problem- closing this PR, will fix and open another

**Pull request closed without merging**
