### PR TITLE
Blog for OpenLiberty/RealWorld

### PR DESCRIPTION
**Pull request by dshimo**
for issue #924

### CODE REVIEW

**Comment by yeekangc** [comment]
@lauracowen, who should be reviewers (besides me) for such a blog post going forward?  Thanks!

**Comment by lauracowen** [comment]
@yeekangc Yes, after you've done a technical review (or second pair of eyes type of thing), @GraceJansen needs to know so that she can organise the editing backlog (there are 2-3 things on there already - need Zenhub to view) by priority. Then Charlotte or David (or possibly another ID person) will review/edit it ready for publication. Grace will schedule when it should be published.

So, overall, it's Grace you need to notify but then it will be down to prioritisation as to when it will be reviewed/published. But if there's a particular date that it must (or must not) be available, put that in the issue that goes on the backlog (see the [instructions](https://github.com/OpenLiberty/blogs/blob/prod/README.md#Authors-creating-a-new-blog-post).

Actually, also see the [instructions](https://github.com/OpenLiberty/blogs/blob/prod/README.md#Authors-creating-a-new-blog-post) for info about branches - you need to work in a branch in the `blogs` repo then PR that to `draft` so that the editors can work collaboratively with you.

**Review by yeekangc — APPROVED** [review]
LGTM technically.

**Comment by yeekangc** [comment]
@dshimo, can you add a summary before asking readers to try what you have?

In any case, I am good for this to move forward to prioritization and editing.  Cc @GraceJansen

**Comment by gljrobinson** [comment]
@dshimo and @yeekangc 
Great to hear that this is ready to take forward. In order to do this, @yeekangc you need to merge this approved PR into the draft branch and then @dshimo needs to create a new PR to the staging branch. Please tag me in a comment in this new PR so that I know this new PR has been created and then this is the PR that will be used by the editing team going forward.

**Comment by yeekangc** [comment]
PR merged into `draft`.  @dshimo, please prepare the PR for `staging` as Grace noted and tag her when ready.

**Pull request merged**
